micronaut:
  server:
    port: 8081
  application:
    name: learning-markt-backend
netty:
  default:
    allocator:
      max-order: 3
kafka:
  bootstrap:
    servers: localhost:32092
  state:
    dir: "/home/user/Downloads/State"


topics:
  command: "learning-markt-command"
  internalEvent: "learning-markt-internal-event"
  externalEvent: "learning-markt-external-event"
  validation: "learning-markt-validation"
  state: "learning-markt-state"

stores:
  stateStore: markt-store