micronaut:
  server:
    port: 8081
  application:
    name: learning-vertrag-backend
netty:
  default:
    allocator:
      max-order: 3
kafka:
  bootstrap:
    servers: localhost:32092
  state:
    dir: "/home/jonas/Downloads/State"


topics:
  command: learning-vertrag-command
  internalEvent: learning-vertrag-internal-event
  externalEvent: learning-vertrag-external-event
  validation: learning-vertrag-validation
  state: learning-vertrag-state

stores:
  stateStore: vertrag