micronaut:
  application:
    name: vertragBackend
netty:
  default:
    allocator:
      max-order: 3
kafka:
  bootstrap:
    servers: tier.laser.internal:32092

topics:
  command: learning-vertrag-command
  internalEvent: learning-vertrag-internal-event
  externalEvent: learning-vertrag-external-event
  state: learning-vertrag-state

stores:
  vertragStore: vertrag